# Generated by Django 5.0.6 on 2026-08-31 02:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vapi_call_id', models.CharField(help_text='Unique call session ID from Vapi AI', max_length=255, unique=True)),
                ('caller_phone', models.CharField(max_length=30)),
                ('call_status', models.CharField(default='completed', max_length=50)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('summary', models.TextField(blank=True, help_text='AI-generated incident and injury triage summary')),
                ('transcript', models.TextField(blank=True, help_text='Complete dialogue transcript between AI assistant and caller')),
                ('recording_url', models.URLField(blank=True, help_text='S3 / Vapi hosted audio recording MP3 URL', max_length=1000, null=True)),
                ('priority', models.CharField(default='HIGH', help_text='Triage priority (CRITICAL, HIGH, MEDIUM, LOW)', max_length=20)),
                ('sent_to_support', models.BooleanField(default=False, help_text='Flag indicating whether handoff email was dispatched to support team')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('incident_id', models.CharField(help_text='External unique incident identifier from traffic feed or n8n', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('source', models.CharField(default='GDOT', help_text='Traffic feed source (e.g. GDOT, 511_GA, NaviGAtor)', max_length=100)),
                ('incident_type', models.CharField(default='Collision', help_text='Type of incident (e.g. Collision, Multi-car Accident, Vehicle Fire)', max_length=150)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='GPS Latitude of the incident', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='GPS Longitude of the incident', max_digits=9)),
                ('city_area', models.CharField(help_text='Highway corridor or municipal area (e.g. I-85 North near Spaghetti Junction)', max_length=255)),
                ('occurred_at', models.DateTimeField(help_text='Timestamp when the incident was reported')),
                ('target_radius_miles', models.IntegerField(default=5, help_text='Calculated contextual ad target radius in miles (5 to 10 miles)')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active Incident'), ('CAMPAIGN_TRIGGERED', 'Campaign Triggered'), ('CLOSED', 'Closed / Cleared')], default='ACTIVE', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['status', 'occurred_at'], name='core_incide_status_543c5a_idx'), models.Index(fields=['latitude', 'longitude'], name='core_incide_latitud_362b3c_idx')],
            },
        ),
        migrations.CreateModel(
            name='GeoCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('GOOGLE_ADS', 'Google Ads (Search & Performance Max)'), ('META_ADS', 'Meta Ads (Facebook & Instagram Feed)')], max_length=30)),
                ('external_campaign_id', models.CharField(blank=True, help_text='Google/Meta external campaign ID', max_length=255, null=True)),
                ('ad_set_or_group_id', models.CharField(blank=True, help_text='Ad set or ad group ID', max_length=255, null=True)),
                ('budget_daily', models.DecimalField(decimal_places=2, default=50.0, help_text='Daily budget allocation in USD', max_digits=8)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Deployment'), ('ACTIVE', 'Active Serving'), ('PAUSED', 'Paused'), ('FAILED', 'Launch Failed')], default='PENDING', max_length=30)),
                ('raw_response', models.JSONField(blank=True, help_text='API response payload from ad network', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='core.incident')),
            ],
        ),
        migrations.CreateModel(
            name='FormLead',
            fields=[
                ('lead_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('preferred_contact', models.CharField(default='PHONE', max_length=50)),
                ('message', models.TextField(blank=True)),
                ('trustedform_cert_url', models.URLField(blank=True, help_text='TrustedForm certificate token URL proving voluntary consumer consent', max_length=1000, null=True)),
                ('user_consent', models.BooleanField(default=False, help_text='Explicit TCPA consent acknowledgment checkbox')),
                ('sent_to_support', models.BooleanField(default=False, help_text='Flag indicating whether handoff email was dispatched to support')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_leads', to='core.geocampaign')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_leads', to='core.incident')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('IMAGE', 'Crash Image / Screenshot'), ('VIDEO', 'Traffic Camera Video Stream / MP4')], default='IMAGE', max_length=20)),
                ('source_url', models.URLField(help_text='Original public URL provided by GDOT / camera feed', max_length=1000)),
                ('file', models.FileField(blank=True, help_text='Persisted file in S3 / Django media storage', null=True, upload_to='crash_media/%Y/%m/%d/')),
                ('file_size_bytes', models.BigIntegerField(blank=True, help_text='Size of the downloaded asset in bytes', null=True)),
                ('download_status', models.CharField(choices=[('PENDING', 'Pending Download'), ('DOWNLOADING', 'In Progress'), ('COMPLETED', 'Successfully Stored'), ('FAILED', 'Download Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error trace if download failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='core.incident')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
