# Generated by Django 5.0.6 on 2026-09-07 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(db_index=True, help_text='Persistent visitor UUID across sessions', max_length=100)),
                ('session_id', models.CharField(db_index=True, help_text='Unique browsing session identifier (30-min window)', max_length=150, unique=True)),
                ('visit_number', models.PositiveIntegerField(default=1, help_text='Sequential visit counter (1 = First Visit, 2 = Second Visit, etc.)')),
                ('is_returning', models.BooleanField(default=False, help_text='Indicates whether this visit is from a returning visitor')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Public IP address of the visitor', null=True)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('region_state', models.CharField(blank=True, default='', help_text='State or province (e.g. Georgia, GA)', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=150)),
                ('postal_code', models.CharField(blank=True, default='', max_length=30)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Estimated latitude from IP geolocation', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Estimated longitude from IP geolocation', max_digits=9, null=True)),
                ('timezone', models.CharField(blank=True, default='', max_length=100)),
                ('isp', models.CharField(blank=True, default='', help_text='Internet Service Provider / Carrier (e.g. AT&T, Verizon)', max_length=255)),
                ('device_type', models.CharField(default='UNKNOWN', help_text='Device category: MOBILE, DESKTOP, TABLET, BOT', max_length=50)),
                ('browser', models.CharField(blank=True, default='', max_length=100)),
                ('os', models.CharField(blank=True, default='', max_length=100)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('screen_resolution', models.CharField(blank=True, default='', max_length=50)),
                ('language', models.CharField(blank=True, default='', max_length=50)),
                ('page_url', models.URLField(blank=True, default='', help_text='Full visited URL', max_length=1000)),
                ('page_path', models.CharField(blank=True, default='/', max_length=255)),
                ('referrer', models.URLField(blank=True, default='', help_text='Referrer source URL', max_length=1000)),
                ('utm_source', models.CharField(blank=True, default='', max_length=100)),
                ('utm_medium', models.CharField(blank=True, default='', max_length=100)),
                ('utm_campaign', models.CharField(blank=True, default='', max_length=150)),
                ('utm_term', models.CharField(blank=True, default='', max_length=150)),
                ('utm_content', models.CharField(blank=True, default='', max_length=150)),
                ('gclid', models.CharField(blank=True, default='', help_text='Google Ads Click ID', max_length=255)),
                ('fbclid', models.CharField(blank=True, default='', help_text='Meta Ads Click ID', max_length=255)),
                ('clicked_elements', models.JSONField(blank=True, default=list, help_text='Chronological list of clicked elements, CTA buttons, and user actions in this session')),
                ('interaction_summary', models.TextField(blank=True, default='', help_text='Summary of notable user actions in this session')),
                ('visited_at', models.DateTimeField(auto_now_add=True, help_text='Session start timestamp')),
                ('last_activity_at', models.DateTimeField(auto_now=True, help_text='Most recent activity timestamp in this session')),
                ('campaign', models.ForeignKey(blank=True, help_text='Associated GeoCampaign', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors', to='core.geocampaign')),
                ('incident', models.ForeignKey(blank=True, help_text='Highway crash incident linked via ad click / UTM params', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors', to='core.incident')),
            ],
            options={
                'ordering': ['-visited_at'],
                'indexes': [models.Index(fields=['visitor_id', '-visited_at'], name='core_websit_visitor_8157d3_idx'), models.Index(fields=['session_id'], name='core_websit_session_c51143_idx'), models.Index(fields=['ip_address', 'visited_at'], name='core_websit_ip_addr_531767_idx'), models.Index(fields=['region_state', 'city'], name='core_websit_region__471815_idx'), models.Index(fields=['device_type'], name='core_websit_device__72247e_idx')],
            },
        ),
    ]
