# Generated by Django 5.0.6 on 2026-09-07 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_websitevisitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_name', models.CharField(choices=[('INCIDENT_POLLER', '1. Incident Poller & Geo Target'), ('AD_CAMPAIGN_TRIGGER', '2. Ad Campaign Trigger (Google / Meta)'), ('FORM_LEAD_INTAKE', '3. Form Lead Intake & Consent'), ('VAPI_CALL_HANDOFF', '4. Vapi AI Voice Call Handoff')], db_index=True, help_text='The automated workflow pipeline executing this step', max_length=60)),
                ('stage', models.CharField(choices=[('INCIDENT_DETECTED', 'Incident Detected & Ingested'), ('GEO_RADIUS_CALCULATED', '5-10 Mile Radius Assigned'), ('CAMPAIGN_LIVE', 'Ad Campaign Live & Serving'), ('LEAD_CAPTURED', 'Lead Captured & Validated'), ('SENT_TO_SUPPORT', 'Email Dispatched to Support Team'), ('EXECUTION_FAILED', 'Execution Error Encountered')], help_text='Specific lifecycle milestone reached', max_length=60)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success / Verified'), ('IN_PROGRESS', 'In Progress / Queued'), ('FAILED', 'Failed / Error'), ('WARNING', 'Warning / Partial')], db_index=True, default='SUCCESS', help_text='Execution health status', max_length=30)),
                ('execution_time_ms', models.IntegerField(default=0, help_text='Duration of this workflow step in milliseconds')),
                ('error_message', models.TextField(blank=True, help_text='Exception trace or API error details if failed', null=True)),
                ('payload_snapshot', models.JSONField(blank=True, default=dict, help_text='Input parameters, response payloads, or audit metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Exact timestamp of this workflow execution step')),
                ('call_lead', models.ForeignKey(blank=True, help_text='Associated Vapi AI phone call', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_statuses', to='core.calllead')),
                ('campaign', models.ForeignKey(blank=True, help_text='Associated Google/Meta geo campaign', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_statuses', to='core.geocampaign')),
                ('form_lead', models.ForeignKey(blank=True, help_text='Associated landing page form submission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_statuses', to='core.formlead')),
                ('incident', models.ForeignKey(blank=True, help_text='Associated crash incident', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_statuses', to='core.incident')),
            ],
            options={
                'verbose_name': 'Workflow Status',
                'verbose_name_plural': 'Workflow Statuses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workflow_name', 'status'], name='core_workfl_workflo_af15db_idx'), models.Index(fields=['-created_at'], name='core_workfl_created_e4af95_idx')],
            },
        ),
    ]
